name1= input("What is your name?_")
name2= input("What is His/Her name?_")
a = (name1+name2.lower())
print(a)
true =(a.count("t")+a.count("r")+a.count("u")+a.count("e"))
love =(a.count("l")+a.count("o")+a.count("v")+a.count("e"))
love_score = str(true)+str(love)
percent =(love_score+"%")
print(percent)
print(int(love_score))